INSERT INTO She_standard_catalog(name)
VALUES      ("POLITICA de SHE"),
            ("Revisión de la Administración"),
            ("Accidentes, Incidentes y No conformidades"),
            ("Evaluación de riesgos"),
            ("Cumplimiento de REQUISITOS LEGALES"),
            ("OBJETIVOS Y METAS"),
            ("ADMINISTRACIÓN DEL PROGRAMA"),
            ("ESTRUCTURA Y RESPONSABILIDAD"),
            ("ENTRENAMIENTO"),
            ("COMUNICACIÓN"),
            ("DOCUMENTACION"),
            ("SISTEMA CONTROL DE DOCUMENTOS"),
            ("EQUIPOS A PRESION CRITICA"),
            ("Estandar de seguridad en viajes y vehículos"),
            ("Estandar de seguridad eléctrica+B20:B40"),
            ("Estandar de trabajo en alturas"),
            ("Compras / Proveedores"),
            ("Materiales Peligrosos/incluye materia prima"),
            ("Maquinaria. equipo y materiales"),
            ("Almacenamiento"),
            ("Equipo y vehículos de transporte interno"),
            ("Contratistas"),
            ("Comportamientos seguros"),
            ("Tareas Peligrosas-criticas"),
            ("Diseño. modificaciones de planta/procesos nuevos/equipos MOC"),
            ("Mantenimiento de planta (área de trabajo y el equipo)"),
            ("Equipos y sistemas de protección de seguridad y salud"),
            ("Equipo de protección personal"),
            ("Aspectos de salud"),
            ("Estandar de ruido en el lugar de trabajo"),
            ("Preparación y respuesta a emergencia"),
            ("Medición y Monitoreo y Desempeño"),
            ("INVESTIGACION DE INCIDENTES y NO CONFORMIDADES"),
            ("AUDITORÍA")
  