
INSERT INTO event(description,id_branch) VALUES ('Falla eje porta bobina',33);
INSERT INTO event(description,id_branch) VALUES ('Falla de servomotor',33);
INSERT INTO event(description,id_branch) VALUES ('Falla en freno de portabobina',33);
INSERT INTO event(description,id_branch) VALUES ('Falla rodillos de desbobinado',33);
INSERT INTO event(description,id_branch) VALUES ('Daño triángulo formador',33);
INSERT INTO event(description,id_branch) VALUES ('fallo en sensor de balansin',33);
INSERT INTO event(description,id_branch) VALUES ('Daño rodillos guía',33);
INSERT INTO event(description,id_branch) VALUES ('Falla bomba',36);
INSERT INTO event(description,id_branch) VALUES ('Falla en sensor de nivel',36);
INSERT INTO event(description,id_branch) VALUES ('Fallo en tarjetas de dosificado',36);
INSERT INTO event(description,id_branch) VALUES ('Falla en flujómetros',36);
INSERT INTO event(description,id_branch) VALUES ('Falla en sistema de presurización de la tolva',36);
INSERT INTO event(description,id_branch) VALUES ('falla en electrovalvulas',36);
INSERT INTO event(description,id_branch) VALUES ('Falla en válvula de recirculación',36);
INSERT INTO event(description,id_branch) VALUES ('Falla en la RTD´s',36);
INSERT INTO event(description,id_branch) VALUES ('Daño en boquillas',36);
INSERT INTO event(description,id_branch) VALUES ('Falla sello vertical',107);
INSERT INTO event(description,id_branch) VALUES ('Falla de resorte, enganches y esparragos',107);
INSERT INTO event(description,id_branch) VALUES ('Falla en respaldar',107);
INSERT INTO event(description,id_branch) VALUES ('Falla en rotulas',107);
INSERT INTO event(description,id_branch) VALUES ('Falla en barrilla de tensión',107);
INSERT INTO event(description,id_branch) VALUES ('Falla en mordaza',107);
INSERT INTO event(description,id_branch) VALUES ('Falla en relé de estado solido',107);
INSERT INTO event(description,id_branch) VALUES ('Falla en bujes',107);
INSERT INTO event(description,id_branch) VALUES ('Falla en leva',107);
INSERT INTO event(description,id_branch) VALUES ('Falla en rol seguidor de leva',107);
INSERT INTO event(description,id_branch) VALUES ('Daño cuchilla',109);
INSERT INTO event(description,id_branch) VALUES ('Falla en sello horizontal',108);
INSERT INTO event(description,id_branch) VALUES ('Falla de resorte, enganches y esparragos',108);
INSERT INTO event(description,id_branch) VALUES ('Falla en respaldar',108);
INSERT INTO event(description,id_branch) VALUES ('Falla en rotulas',108);
INSERT INTO event(description,id_branch) VALUES ('Falla en barrilla de tensión',108);
INSERT INTO event(description,id_branch) VALUES ('Falla en mordaza',108);
INSERT INTO event(description,id_branch) VALUES ('Falla en relé de estado solido',108);
INSERT INTO event(description,id_branch) VALUES ('Falla en bujes',108);
INSERT INTO event(description,id_branch) VALUES ('Falla en leva',108);
INSERT INTO event(description,id_branch) VALUES ('Falla en rol seguidor de leva',108);
INSERT INTO event(description,id_branch) VALUES ('Daño cuchilla / fallo en abre facil',110);
INSERT INTO event(description,id_branch) VALUES ('Falla de resorte, enganches y esparragos',111);
INSERT INTO event(description,id_branch) VALUES ('Falla en rotulas',111);
INSERT INTO event(description,id_branch) VALUES ('Falla en barrilla de tensión',111);
INSERT INTO event(description,id_branch) VALUES ('Falla en mordaza',111);
INSERT INTO event(description,id_branch) VALUES ('Falla en relé de estado solido',111);
INSERT INTO event(description,id_branch) VALUES ('Falla en bujes',111);
INSERT INTO event(description,id_branch) VALUES ('Falla en leva',111);
INSERT INTO event(description,id_branch) VALUES ('Falla en rol seguidor de leva',111);
INSERT INTO event(description,id_branch) VALUES ('Falla sello fondo',111);
INSERT INTO event(description,id_branch) VALUES ('Falla motor',113);
INSERT INTO event(description,id_branch) VALUES ('Falla variador',113);
INSERT INTO event(description,id_branch) VALUES ('Falla de clutchs',113);
INSERT INTO event(description,id_branch) VALUES ('fallo en reductor',113);
INSERT INTO event(description,id_branch) VALUES ('fallo en arbol de levas',113);
INSERT INTO event(description,id_branch) VALUES ('Falla en chiller de enfriamiento',37);
INSERT INTO event(description,id_branch) VALUES ('Falla en placa de frío',37);
INSERT INTO event(description,id_branch) VALUES ('falla por fugas u obstruccion de mangueras de agua',37);
INSERT INTO event(description,id_branch) VALUES ('Falla en rotulas',37);
INSERT INTO event(description,id_branch) VALUES ('Falla en barrilla de tensión',37);
INSERT INTO event(description,id_branch) VALUES ('Falla en mordaza',37);
INSERT INTO event(description,id_branch) VALUES ('Falla en bujes',37);
INSERT INTO event(description,id_branch) VALUES ('Falla en leva',37);
INSERT INTO event(description,id_branch) VALUES ('Falla en rol seguidor de leva',37);
INSERT INTO event(description,id_branch) VALUES ('Falla sello fondo',37);
INSERT INTO event(description,id_branch) VALUES ('Quiebra de carro móvil',114);
INSERT INTO event(description,id_branch) VALUES ('Falla en pinzas carro móvil',114);
INSERT INTO event(description,id_branch) VALUES ('quiebra de patines de los carros moviles',114);
INSERT INTO event(description,id_branch) VALUES ('quiebra de brazo de carros moviles',114);
INSERT INTO event(description,id_branch) VALUES ('quiebra de los tornillos de sugesion de los carros',114);
INSERT INTO event(description,id_branch) VALUES ('quiebra del rolles seguidores de levas',114);
INSERT INTO event(description,id_branch) VALUES ('quiebra de esparragos en sistema de levas',114);
INSERT INTO event(description,id_branch) VALUES ('quiebra de enganches de sistema de levas',114);
INSERT INTO event(description,id_branch) VALUES ('quiebra de leva de carros moviles',114);
INSERT INTO event(description,id_branch) VALUES ('quiebra de resortes  en sistema de levas',114);
INSERT INTO event(description,id_branch) VALUES ('quiebra de roles de las bases de los carros moviles',114);
INSERT INTO event(description,id_branch) VALUES ('quiebra de pickman de los brazos moviles',114);
INSERT INTO event(description,id_branch) VALUES ('quiebra de rotulas de brazos moviles',114);
INSERT INTO event(description,id_branch) VALUES ('falla en el reductor de los carros moviles UGI',114);
INSERT INTO event(description,id_branch) VALUES ('Quiebra de carro fijo',115);
INSERT INTO event(description,id_branch) VALUES ('Falla en pinzas carro fijo',115);
INSERT INTO event(description,id_branch) VALUES ('falla en pinzas de estirado',115);
INSERT INTO event(description,id_branch) VALUES ('falla por cambio de roles del sistema de estirado',115);
INSERT INTO event(description,id_branch) VALUES ('quiebra de esparragos en sistema de levas',115);
INSERT INTO event(description,id_branch) VALUES ('quiebra por cambio de ugis',115);
INSERT INTO event(description,id_branch) VALUES ('quiebra por cambio de ejes de los carros fijos',115);
INSERT INTO event(description,id_branch) VALUES ('quiebra de resortes  en sistema de levas',115);
INSERT INTO event(description,id_branch) VALUES ('quiebra de enganches de sistema de levas',115);
INSERT INTO event(description,id_branch) VALUES ('quiera de leva de carros fijos',115);
INSERT INTO event(description,id_branch) VALUES ('falla en eje central del brazo de arrastre',33);
INSERT INTO event(description,id_branch) VALUES ('falla en rotulas del sistema de arrastre',33);
INSERT INTO event(description,id_branch) VALUES ('quiebra de pickman del sistema de arrastre',33);
INSERT INTO event(description,id_branch) VALUES ('quiebra por cambio de clotch de sistema de arrastre',33);
INSERT INTO event(description,id_branch) VALUES ('quiebra resorte  y enganche de sistema de arrastre',33);
INSERT INTO event(description,id_branch) VALUES ('Falla en brazo arrastre',33);
INSERT INTO event(description,id_branch) VALUES ('Falla motor',116);
INSERT INTO event(description,id_branch) VALUES ('fallo en reductor',116);
INSERT INTO event(description,id_branch) VALUES ('quiebra de piñones plastidos de traccion de la banda',116);
INSERT INTO event(description,id_branch) VALUES ('cambio de piñones de cadena de traccion',116);
INSERT INTO event(description,id_branch) VALUES ('quiebra de cadena de traccion',116);
INSERT INTO event(description,id_branch) VALUES ('falla en las guias de la banda',116);
INSERT INTO event(description,id_branch) VALUES ('falla en cableado electrico',116);
INSERT INTO event(description,id_branch) VALUES ('fallo en banda',116);
INSERT INTO event(description,id_branch) VALUES ('Falla variador',116);
INSERT INTO event(description,id_branch) VALUES ('Quiebra sistema de vacío',117);
INSERT INTO event(description,id_branch) VALUES ('cambio de electrovalvula',117);
INSERT INTO event(description,id_branch) VALUES ('cambio de acoples neumaticos',117);
INSERT INTO event(description,id_branch) VALUES ('cambio de pickman de sistema de apertura',117);
INSERT INTO event(description,id_branch) VALUES ('cambio de rulinas sistema de apertura',117);
INSERT INTO event(description,id_branch) VALUES ('cambio de roles sistema de apertura',117);
INSERT INTO event(description,id_branch) VALUES ('cambio de varrillas con desgaste',117);
INSERT INTO event(description,id_branch) VALUES ('cambio de rotulas sistema de apertura',117);
INSERT INTO event(description,id_branch) VALUES ('cambio de ventury',117);
INSERT INTO event(description,id_branch) VALUES ('Quiebra Sistema eléctrico',118);
INSERT INTO event(description,id_branch) VALUES ('cambio de variadores',118);
INSERT INTO event(description,id_branch) VALUES ('cambio de electrovalvulas',118);
INSERT INTO event(description,id_branch) VALUES ('cambio de relays de estado solido',118);
INSERT INTO event(description,id_branch) VALUES ('revision de programa del plc por fallos',118);
INSERT INTO event(description,id_branch) VALUES ('reemplazo de modulos del plc',118);
INSERT INTO event(description,id_branch) VALUES ('cambio de proteccion termica',118);
INSERT INTO event(description,id_branch) VALUES ('cambio de disyuntor termico',118);
INSERT INTO event(description,id_branch) VALUES ('cambio de cableado electrico por recalentamiento',118);
INSERT INTO event(description,id_branch) VALUES ('cambio de fusibles por corto electrico',118);
INSERT INTO event(description,id_branch) VALUES ('cambio de relays 24vdc',118);
INSERT INTO event(description,id_branch) VALUES ('Quiebra Sistema neumático',119);
INSERT INTO event(description,id_branch) VALUES ('cambio de electrovalvulas',119);
INSERT INTO event(description,id_branch) VALUES ('cambio de mangueras neumaticas',119);
INSERT INTO event(description,id_branch) VALUES ('Falla PLC',120);
INSERT INTO event(description,id_branch) VALUES ('Falla codificador',121);
INSERT INTO event(description,id_branch) VALUES ('Quiebra en el núcleo del codificador',121);
INSERT INTO event(description,id_branch) VALUES ('Quiebra en sistema de recuperación de solvente',121);
INSERT INTO event(description,id_branch) VALUES ('Balancín',122);
INSERT INTO event(description,id_branch) VALUES ('Caja reductoras(superior e inferior)',122);
INSERT INTO event(description,id_branch) VALUES ('Sistema de herramienta',122);
INSERT INTO event(description,id_branch) VALUES ('Paletas gripper',122);
INSERT INTO event(description,id_branch) VALUES ('Roles de ejes ventosas',122);
INSERT INTO event(description,id_branch) VALUES ('Ventosas',122);
INSERT INTO event(description,id_branch) VALUES ('Pistón slip sheet',122);
INSERT INTO event(description,id_branch) VALUES ('Sensores de posición',122);
INSERT INTO event(description,id_branch) VALUES ('Pistón gripper',122);
INSERT INTO event(description,id_branch) VALUES ('Tarjeta servocontroladora',122);
INSERT INTO event(description,id_branch) VALUES ('Cortinas de seguridad',122);
INSERT INTO event(description,id_branch) VALUES ('Motores de banda salida',122);
INSERT INTO event(description,id_branch) VALUES ('Rodillos salida',122);
INSERT INTO event(description,id_branch) VALUES ('Radar de seguridad',122);
INSERT INTO event(description,id_branch) VALUES ('Sensores de tarima',122);
INSERT INTO event(description,id_branch) VALUES ('Servomotores',122);
INSERT INTO event(description,id_branch) VALUES ('Electrovalvulas',122);
INSERT INTO event(description,id_branch) VALUES ('Uñas de tarima',122);
INSERT INTO event(description,id_branch) VALUES ('Barra de trasmisión de uñas',122);
INSERT INTO event(description,id_branch) VALUES ('Muñoras',122);
INSERT INTO event(description,id_branch) VALUES ('Sensor de altura de tarimas',122);
INSERT INTO event(description,id_branch) VALUES ('Sistema electrico',122);
INSERT INTO event(description,id_branch) VALUES ('teach pendant',122);
INSERT INTO event(description,id_branch) VALUES ('Sistema neumatico',122);
INSERT INTO event(description,id_branch) VALUES ('Controlador del robot',122);
INSERT INTO event(description,id_branch) VALUES ('HMI',122);
INSERT INTO event(description,id_branch) VALUES ('Llavines de entrada',122);
INSERT INTO event(description,id_branch) VALUES ('Falla en sub estaciones eléctricas',38);
INSERT INTO event(description,id_branch) VALUES ('Falta de agua',38);
INSERT INTO event(description,id_branch) VALUES ('Falta de vapor',38);
INSERT INTO event(description,id_branch) VALUES ('Ajuste de freno del porta bobina',66);
INSERT INTO event(description,id_branch) VALUES ('Limpieza de freno del porta bobinas',66);
INSERT INTO event(description,id_branch) VALUES (NULL,66);
INSERT INTO event(description,id_branch) VALUES ('Ajuste de posición de fotoceldas',66);
INSERT INTO event(description,id_branch) VALUES ('Limpieza de fotocelda',66);
INSERT INTO event(description,id_branch) VALUES ('Ajuste de triángulo formador',66);
INSERT INTO event(description,id_branch) VALUES ('Ajuste de presión de rodillos',66);
INSERT INTO event(description,id_branch) VALUES ('Limpieza de rodillos',66);
INSERT INTO event(description,id_branch) VALUES ('Ajuste de posición de boquilla',71);
INSERT INTO event(description,id_branch) VALUES ('Ajuste de altura de boquilla',71);
INSERT INTO event(description,id_branch) VALUES ('Ajuste de temperaura',71);
INSERT INTO event(description,id_branch) VALUES ('Ajuste de sensibilidad de sensor de nivel de tolva',71);
INSERT INTO event(description,id_branch) VALUES ('Limpieza de boquillas',71);
INSERT INTO event(description,id_branch) VALUES ('Limpieza de sello vertical',67);
INSERT INTO event(description,id_branch) VALUES ('Limpieza de sello fondo',67);
INSERT INTO event(description,id_branch) VALUES ('Limpieza de sello horizontal',67);
INSERT INTO event(description,id_branch) VALUES ('Limpieza de sello ultrasonico',67);
INSERT INTO event(description,id_branch) VALUES ('Ajuste de temperatura de sello vertical',67);
INSERT INTO event(description,id_branch) VALUES ('Ajuste de temperatura de sello horizontal',67);
